#!/bin/sh
# gen_ksyms.sh — generate C source for the embedded kernel symbol table.
#
# Reads a linked ELF, walks its text-segment symbols in address order,
# and emits a C source file with two arrays:
#     const struct ksym ksyms[]     — { uint64_t addr; uint32_t name_off; }
#     const char        ksym_strs[] — NUL-terminated names back-to-back
#     const uint32_t    ksym_count
#
# Addresses are written as 0x-prefixed literals straight from nm, so no
# hex arithmetic in awk is required (portable across mawk/gawk/bwk).
#
# Usage: gen_ksyms.sh build/lighthos.stage1.bin > build/ksyms_data.c
set -eu

BIN="${1:?usage: gen_ksyms.sh <kernel.elf>}"
TMP="build/ksyms.nm.tmp"

# Text (T/t) and weak-text (W/w) only. Drop compiler/linker tmp names.
x86_64-elf-nm -n --defined-only "$BIN" | \
    awk '$2 ~ /^[TtWw]$/ && $3 ~ /^[A-Za-z_]/ { print }' > "$TMP"

cat <<'EOF'
/* auto-generated by tools/gen_ksyms.sh — do not edit by hand.
 * Two stages of the kernel link: (1) stage1 without this file,
 * (2) stage2 with it appended to .rodata so function RIPs stay
 * addressable from the embedded table. */
#include "include/types.h"

struct ksym { uint64_t addr; uint32_t name_off; };

const char ksym_strs[] =
EOF

awk '{ printf "    \"%s\\0\"\n", $3 }' "$TMP"

cat <<'EOF'
    ;

const struct ksym ksyms[] = {
EOF

awk 'BEGIN { off = 0 }
     {
         printf "    { 0x%s, %d },\n", $1, off
         off += length($3) + 1
     }' "$TMP"

cat <<'EOF'
};
EOF

awk 'END { printf "const uint32_t ksym_count = %d;\n", NR }' "$TMP"

rm -f "$TMP"
